### PR TITLE
pyre.primitives.path.stems: to obtain the file name without suffix

### PR DESCRIPTION
**Pull request by lijun99**
add a method to obtain the file name without the (last) suffix
e.g., file=pyre.primitives.path('pyre/test/name.data.txt')
file.stem return name
file.stems return name.data

Related to Issues #25.

### CODE REVIEW

**Comment by aivazis** [comment]
How about

@property
def stems(self):
   return self.name.split('.')

and letting the user pick the one they want?

We should also check whether

@property
def stem(self):
    return self.name.split('.')[0]

is any slower than the slightly more involved logic in the current implementation

**Comment by lijun99** [comment]
My intention was to use something like withSuffix, to replace suffix upon file format conversion (e.g., text, binary, hdf5), similar to with_suffix in pathlib. But since we need to keep the pyre stem definition as it is for now, I will use nameStem to be equivalent to pathlib.stem. Now withSuffix is doing the same as the pathlib with_suffix. 

stems (or name in split form) then is not necessary since users can call name and split by one command. 

Performance is not a concern for me since these methods are not expected to be called a lot. 

Please check my updates.

**Comment by lijun99** [comment]
If we change the definition of path.stem to be the same as pathlib, i.e., the filename without the last suffix, it was found that AlTar-1.1 breaks down. The cause is from pyre/config/ODB.py/interpret: symbol = path.stem; which is called by pyre/framework/Linker.py. It wants to interpret altar.rng.gsl as altar, not altar.rng. 

Please decide
1) to use pathlib definition of stem; i.e., stem of altar.bayesian.sampler is altar.bayesian; 
the required changes are in the newest commit of path.stems, 8c03682.
2) to keep stem as it is; i.e., stem of altar.bayesian.sampler is altar, 
please provide a new method for do what 1) does; e.g., replacing nameStem to an appropriate name in ad92156. 

Please also note that changing the definition of stem will affect withSuffix method.

**Comment by lijun99** [comment]
Please also consider the change to pyre/config/ODB.py/interpret; it is the only place I found that will be affected by the change of stem definition.

**Comment by lijun99** [comment]
Michael, could you please change the packages/pyre/config/odb/ODB.py as well because we have changed the definition of stem (used to be the name without all suffixes, now the name without the last suffix)?
 
def interpret(cls, request):
    ...
    symbol = path.stem
    ...

to something like symbol = path.name.split('.')[0] 

AlTar-1.1 needs this to work. 
 
Thanks!

**Pull request closed without merging**
